[[server]]
    port = 8000
    
# this is a comment skip it
    server_name = "webserv.com" 
    root = "www/index.html"
    client_max_body_size = "1G"
    [[server.error_page]]
        413 = "errors/index_400.html"
#       403 = "errors/4xx.html"
#       501 = "errors/5xx.html"
#       500 = "errors/5xx.html"
#       502 = "errors/5xx.html"
#       503 = "errors/5xx.html"
#       504 = "errors/5xx.html"

# this location will redirect you to the url.

    [[server.location]]
        uri = "/redirecting"
        return = 301 https://www.google.com
    
    [[server.location]]
        uri = "/uploading"
		root = "www/upload"
        index = ["index.html"]
        allow_methods = ["GET", "POST"]
		post_module = "enable"
    
    [[server.location]]
        uri = "/website"
        allow_methods = ["GET", "POST"]
        index = ["index.html", "video.html", "contact.html", "about.html"]
        root = "www/fullywebsite"
    
    [[server.location]]
        uri = "/autoindexing"
		root = "www/testAutoIndex"
        allow_methods = ["GET"]
        autoindex = "ON"

    
    [[server.location]]
       uri = "/cgi_session"
       cgi_extension = ".py"
       root = src/cgi/test1.py
       allow_methods = ["GET", "POST"]



[[server]]
    port = 8001 9000
    host = "127.0.0.1"
    server_name = "webserv1.com" 
    root = "www/index.html"
    client_max_body_size = "2G"


    [[server.error_page]]
        401 = "/errors/4xx.html"
        403 = "/errors/4xx.html"
        501 = "/errors/5xx.html"
        500 = "/errors/5xx.html"
        502 = "/errors/5xx.html"
        503 = "/errors/5xx.html"
        504 = "/errors/5xx.html"

    [[server.location]]
        uri = "/uploading"
		root = "www/upload"
        index = ["index.html"]
        allow_methods = ["GET", "POST"]
		post_module = "enable"

    [[server.location]]
        uri = "/redirecting"
        return = 301 https://www.github.com
    
    [[server.location]]
       uri = "/deleting"
       root = "www/upload
       delete_module = "enable"
       allow_methods = ["GET", "DELETE"]
       index = ["index.html"]