[[server]]
    upload_path =  "www"

    [[server.error_page]]
        401 = " /errors/4xx.html"

    [[server.location]]
        uri = "%.go$"

    [[server.error_page]]
        401 = " /errors/4xx.html"

    [[server.location]]
        uri = "%.py$"

    [[server.location]]
        uri = "/"
        allow_methods = ["GET", "POST"]
        autoindex = "ON"

    [[server.location]]
        uri = "/upload"
        allow_methods = ["GET", "POST", "DELETE"]
        autoindex = "ON"

    [[server.location]]
        uri = "/assets"
        allow_methods = ["GET"]
        autoindex = "ON"

    [[server.location]]
        uri = "/yo"
        allow_methods = ["GET", "POST", "DELETE"]
        autoindex = "ON"
        return = "301 https://www.youtube.com/watch?v=eLaIVnI-N6Q"

    [[server.location]]
        uri = "/redirection"
        return = "301 /test.html"

[[server]]
    port = 9090
    host = "127.0.0.1"
    server_name = "example_2.com"
    root = "INCLUDES"

    [[server.location]]
        uri = "/1337"
        allow_methods = ["GET"]
        autoindex = "ON"

    [[server.error_page]]
        401 = "/errors/4xx.html"

[[server]]
    port = 9000
    host =     "127.0.0.1"
    server_name = "wordpress.com"
    root = "INCLUDES"
    autoindex = "OFF"
    upload_path  = "INCLUDES"

    [[server.error_page]]
        401 = "/errors/4xx.html"
        501 = "/errors/5xx.html"
# listen
# root
# uri
#
#location /php {
#		allowed_methods GET,POST;
#		cgiPath cgi-bin/php-cgi;
#		cgiExt php;
#	}
#location /python {
#	cgiPath /usr/local/bin/python3;
#	cgiExt py;
#}
#
#location cgi-bin {
#      root ./;                                                 # cgi-bin location, mandatory parameter
#      cgi_path /usr/bin/python3 /bin/bash;                     # location of interpreters installed on the current system, mandatory parameter
#      cgi_ext .py .sh;                                         # extensions for executable files, mandatory parameter
#  }
