[[server]]
    port = 8000
    host = "127.0.0.1"
# this is a comment skip it
    server_name = "webserv1.com" "webserv.com"
    root = "www/index.html"
    client_max_body_size = "1G"


    [[server.error_page]]
        400 = "www/html/errors/index_400.html"
        403 = "www/html/errors/index_403.html"
        501 = "www/html/errors/index_501.html"

# this location will redirect you to the url.

    [[server.location]]
        uri = "/redirecting"
        return = 301 https://www.google.com
    
    [[server.location]]
        uri = "/uploading"
		root = "www/upload"
        index = ["index.html"]
        allow_methods = ["GET", "POST"]
		post_module = "enable"
    
    [[server.location]]
        uri = "/website"
        allow_methods = ["GET", "POST"]
        index = ["index.html", "video.html", "contact.html", "about.html"]
        root = "www/fullywebsite"
    
    [[server.location]]
        uri = "/autoindexing"
		root = "www/testAutoIndex"
        allow_methods = ["GET"]
        autoindex = "ON"

    
    [[server.location]]
       uri = "/cgi"
       cgi_extension = ".py"
       root = src/cgi/test1.py


[[server]]
    port = 8001
    host = "127.0.0.1"
    server_name = "webserv.com" "webserv.com"
    root = "www/index.html"
    client_max_body_size = "2G"


    [[server.error_page]]
        401 = "www/html/errors/index_401.html"
        403 = "www/html/errors/index_403.html"
        501 = "www/html/errors/index_501.html"
        500 = "www/html/errors/index_500.html"
        502 = "www/html/errors/index_502.html"
        503 = "www/html/errors/index_503.html"
        504 = "www/html/errors/index_504.html"

    [[server.location]]
        uri = "/uploading"
		root = "www/upload"
        index = ["index.html"]
        allow_methods = ["GET", "POST"]
		post_module = "enable"

    [[server.location]]
        uri = "/redirecting"
        return = 301 https://www.github.com
    
    [[server.location]]
       uri = "/deleting"
       root = "www/upload
       delete_module = "enable"
       allow_methods = ["GET", "DELETE"]
       index = ["index.html"]